version: "1"
services:
  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"
  api-gateway:
    build: ./api-gateway
    ports:
      - "80:8085"
    depends_on:
      - service-registry
      - mongo-db
    environment:
      - PORT=8085
      - EUREKA_URL=http://service-registry:8761/eureka
  personal-service:
    build: ./personal-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db
    environment:
      - PORT=8081
      - DB_URL=jdbc:mysql://mysql-db:3306/personal_service?allowPublicKeyRetrieval=true&useSSL=false
      - GATEWAY_URL=http://api-gateway:8085
      - EUREKA_URL=http://service-registry:8761/eureka
  video-service:
    build: ./video-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql-db
    environment:
      - PORT=8082
      - DB_URL=jdbc:mysql://mysql-db:3306/video_service?allowPublicKeyRetrieval=true&useSSL=false
      - GATEWAY_URL=http://api-gateway:8085
      - EUREKA_URL=http://service-registry:8761/eureka
  notify-service:
    build: ./notify-service
    ports:
      - "3000:3000"
    depends_on:
      - service-registry
      - api-gateway
      - mongo-db
    environment:
      - HOST=notify-service
      - PORT=3000
      - EUREKA_HOST=service-registry
      - DB_HOST=mongo-db
  # Database
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    depends_on:
      - service-registry
  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    depends_on:
      - service-registry
    environment:
      - MYSQL_ROOT_PASSWORD=admin
volumes:
  mongo_data:
  mysql_data:
